contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #snptree channel"
    url: https://nfcore.slack.com/channels/snptree
    about: Discussion about the nf-core/snptree pipeline
